name: string_literal_finder
description: |
  Find non translated strings: Searches all dart files for string literals, excluding non
  translatable strings. Useful for i18n/l10n.
version: 1.0.0-dev.1
homepage: https://github.com/hpoul/string_literal_finder/tree/master/packages/string_literal_finder

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.7.1
  logging: ^1.0.1
  logging_appenders: ^1.0.0
  path: ^1.8.0
  meta: ^1.3.0
  source_gen: ^1.0.2
  string_literal_finder_annotations: ^1.0.0
  args: ^2.1.1
  analyzer_plugin: ^0.6.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.9

executables:
  string_literal_finder:

