name: string_literal_finder
description: |
  Find non translated strings: Searches all dart files for string literals, excluding non translatable strings.
version: 0.1.1+3
homepage: https://github.com/hpoul/string_literal_finder/tree/master/packages/string_literal_finder

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  analyzer: ^0.39.16
  logging: ^0.11.4
  logging_appenders: ^0.4.2+3
  path: ^1.7.0
  meta: ^1.2.2
  source_gen: ^0.9.6
  string_literal_finder_annotations: ^0.1.0
  args: ^1.6.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

executables:
  string_literal_finder:

